import { NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { getListingBySlug } from "@/lib/mockData";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(request: Request, { params }: { params: { slug: string } }) {
  const listing = getListingBySlug(params.slug);
  const doc = new PDFDocument({ margin: 50 });
  const chunks: Uint8Array[] = [];

  doc.on("data", (chunk) => chunks.push(chunk));

  const bufferPromise = new Promise<Buffer>((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
  });

  doc.fontSize(20).text(listing.address || listing.title, { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(12).text(`Location: ${listing.city}, ${listing.state}`);
  doc.text(`Market Status: ${listing.marketStatus}`);
  doc.text(`Strategy: ${listing.strategy || "N/A"}`);
  doc.text(`Asking Price: $${listing.price.toLocaleString()}`);
  doc.text(`Est. Rent: ${listing.estRent ? `$${listing.estRent.toLocaleString()}` : "N/A"}`);
  doc.text(`Cap Rate: ${listing.capRate ? `${listing.capRate}%` : "N/A"}`);
  doc.text(`ARV: ${listing.arv ? `$${listing.arv.toLocaleString()}` : "N/A"}`);

  doc.moveDown();
  doc.fontSize(12).text("Summary", { underline: true });
  doc.fontSize(11).text(
    listing.description ||
      "Zona Desert listing summary placeholder. Replace with live description once data is wired."
  );

  doc.moveDown();
  doc.fontSize(12).text("Highlights", { underline: true });
  (listing.highlights || []).forEach((highlight, index) => {
    doc.text(`${index + 1}. ${highlight}`);
  });

  doc.moveDown();
  doc.text("Generated by Zona Desert", { align: "center", oblique: true });

  doc.end();

  const buffer = await bufferPromise;
  const arrayBuffer = Uint8Array.from(buffer).buffer;
  const url = new URL(request.url);
  const download = url.searchParams.get("download") === "1";

  return new NextResponse(arrayBuffer, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `${download ? "attachment" : "inline"}; filename="deal-pack-${listing.slug}.pdf"`
    }
  });
}
